In [1]:
# let import numpy
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()


# Create a 2-dimensional NumPy array using np.array()


# Create a 3-dimensional Numpy array using np.array()

In [5]:
a1= np.array([2, 3, 4, 5, 6])

In [6]:
a2= np.array([[1, 2, 3],
             [4, 5, 5]])

In [7]:
a3=np.array([[[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]]])

In [8]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)

In [9]:
a1.shape

(5,)

In [10]:
a1.ndim

1

In [11]:
a1.dtype

dtype('int64')

In [12]:
type(a1)

numpy.ndarray

In [13]:
a1.size

5

In [14]:
# Attributes of 2-dimensional array

In [15]:
a2.shape

(2, 3)

In [16]:
a2.dtype

dtype('int64')

In [17]:
a2.size

6

In [18]:
type(a2)

numpy.ndarray

In [19]:
a2.ndim

2

In [20]:
# Attributes of 3-dimensional array

In [21]:
a3.shape

(1, 3, 3)

In [22]:
a3.ndim

3

In [23]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [24]:
a3.size

9

In [25]:
type(a3)

numpy.ndarray

In [26]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

In [27]:
import pandas as pd

In [28]:
df= pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  5

In [29]:
# Create an array of shape (10, 2) with only ones

In [30]:
ones= np.ones(shape=(10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
# Create an array of shape (7, 2, 3) of only zeros

In [32]:
zeros= np.zeros(shape=(7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
# Create an array within a range of 0 and 100 with step 3

In [34]:
range_array= np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [35]:
range_array.shape

(34,)

In [36]:
range_array.size

34

In [37]:
# Create a random array with numbers between 0 and 10 of size

In [38]:
range_array_2= np.arange(0, 10)
range_array_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
# Create a random array of floats between 0 & 1 of shape (3, 5)

In [40]:
float_numpy= np.random.random(size=(3, 5))
float_numpy

array([[0.88471192, 0.94409412, 0.53012452, 0.72092666, 0.35604015],
       [0.59598658, 0.23197601, 0.44108564, 0.45896356, 0.27132168],
       [0.85289103, 0.81903534, 0.8601224 , 0.4971466 , 0.07392156]])

In [41]:
# Set the random seed to 42


# Create a random array of numbers between 0 & 10 of size (4, 6)


In [42]:
np.random.seed(42)

seed_array = np.random.randint(0, 10, size=(4, 6))
seed_array

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [43]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable


# Find the unique numbers in the array you just created

In [44]:
a4= np.random.randint(1, 10, size= (3, 7))
a4

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [45]:
np.unique(a4)

array([1, 2, 3, 4, 5, 7, 9])

In [46]:
a4.size

21

In [47]:
# Find the 0'th index of the latest array you created

In [48]:
a4[0]

array([9, 1, 3, 7, 4, 9, 3])

In [49]:
# Get the first 2 rows of latest array you created
a4[0:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [50]:
# Get the first 2 values of the first 2 rows of the latest array


In [51]:
a4[0][:2]

array([9, 1])

In [52]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

In [53]:
array1= np.random.randint(0, 10, size=(3, 5))
array1

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [54]:
array2= np.ones(shape=(3, 5))
array2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
# Add the two arrays together

In [56]:
# let add them together 
array3=array1 + array2
array3

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [57]:
array3.dtype

dtype('float64')

In [58]:
# Create another array of ones of shape (5, 3)

In [59]:
array4= np.ones(shape=(5, 3))
array4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
# Try add the array of ones and the other most recent array together

In [61]:
array2, array4

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [62]:
array2 + array4

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [67]:
# let reshape 
array2_reshape=array2.reshape(5, 3)
array2_reshape

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [68]:
# Let now add them together
add_array=array2_reshape + array4

In [69]:
# Create another array of ones of shape (3, 5)

In [70]:
ones_2= np.ones(shape=(3, 5))
ones_2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
# Subtract the new array of ones from the other most recent array

In [72]:
add_array_2=ones_2 - add_array.reshape(3, 5)
add_array_2

array([[-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.]])

In [73]:
# Multiply the ones array with the latest array

In [74]:
ones_2 * add_array_2

array([[-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.]])

In [75]:
# Take the latest array to the power of 2 using '**'

In [76]:
add_array_2 ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [77]:
# Do the same thing with np.square()

In [78]:
np.square(add_array_2)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [79]:
# find the mean
np.mean(add_array_2)

-1.0

In [80]:
a4

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [81]:
np.mean(a4)

5.190476190476191

In [82]:
# to confirm our anwers
np.sum(a4)/ a4.size

5.190476190476191

In [83]:
# let find the min and max of our array
np.min(a4)

1

In [84]:
# let find the standard deviation
np.std(a4)

2.665816190910172

In [85]:
np.var(a4)

7.10657596371882

In [86]:
np.sqrt(np.var(a4))

2.665816190910172

In [87]:
# Reshape the latest array to (3, 5, 1)

In [89]:
a4, a4.shape

(array([[9, 1, 3, 7, 4, 9, 3],
        [5, 3, 7, 5, 9, 7, 2],
        [4, 9, 2, 9, 5, 2, 4]]),
 (3, 7))

In [95]:
# let reshape add_array_2
reshape=add_array_2.reshape(3, 5, 1)
reshape

array([[[-1.],
        [-1.],
        [-1.],
        [-1.],
        [-1.]],

       [[-1.],
        [-1.],
        [-1.],
        [-1.],
        [-1.]],

       [[-1.],
        [-1.],
        [-1.],
        [-1.],
        [-1.]]])

In [97]:
reshape.shape

(3, 5, 1)

In [98]:
# Transpose the latest array
reshape.T, reshape.T.shape

(array([[[-1., -1., -1.],
         [-1., -1., -1.],
         [-1., -1., -1.],
         [-1., -1., -1.],
         [-1., -1., -1.]]]),
 (1, 5, 3))

In [99]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

In [100]:
# let set our random seed
np.random.seed(0)

mat1= np.random.randint(0, 10, size=(3, 3))
mat2= np.random.randint(0, 10, size=(3, 2))

mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [101]:
# let view our mat2
mat2

array([[4, 7],
       [6, 8],
       [8, 1]])

In [102]:
# Perform a dot product on the two newest arrays you created

In [104]:
mat1.shape, mat2.shape

((3, 3), (3, 2))

In [103]:
np.dot(mat1, mat2)

array([[ 44,  38],
       [126,  86],
       [ 58,  63]])

In [105]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

In [106]:
math1= np.random.randint(0, 10, size=(4, 3))
math2= np.random.randint(0, 10, size=(4, 3))

In [107]:
math1

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0]])

In [108]:
math2

array([[3, 5, 0],
       [2, 3, 8],
       [1, 3, 3],
       [3, 7, 0]])

In [109]:
math1.shape, math2.shape

((4, 3), (4, 3))

In [110]:
# Perform a dot product on the two newest arrays you created

In [111]:
np.dot(math1, math2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

 We are having a shape error, let find our way aroud it
 the rule of dot product is that the inner number of the shape must be the same and the result is the outside numbers 

In [113]:
math2.T.shape

(3, 4)

In [115]:
# we can solve the by obtaining the transpose of math2
math2_trans= math2.T
math2_trans

array([[3, 2, 1, 3],
       [5, 3, 3, 7],
       [0, 8, 3, 0]])

In [116]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

In [117]:
np.random.seed(42)

b1= np.random.randint(0, 10, size=(3, 5))
b2= np.random.randint(0, 10, size=(3, 5))

In [118]:
b1

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5]])

In [119]:
b2

array([[4, 1, 7, 5, 1],
       [4, 0, 9, 5, 8],
       [0, 9, 2, 6, 3]])

In [120]:
# Compare the two arrays with '>'

In [122]:
bool_array = b1 > b2
bool_array

array([[ True,  True, False, False,  True],
       [ True,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [123]:
b1 >= b2

array([[ True,  True,  True, False,  True],
       [ True,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [124]:
# Find which elements of the first array are greater than 7

In [125]:
b1

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5]])

In [126]:
b1 > 7

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False]])

In [127]:
# Which parts of each array are equal? (try using '==')

In [128]:
b1 == b2

array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [129]:
# Sort one of the arrays you just created in ascending order

In [131]:
b1

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5]])

In [133]:
new_array= np.sort(b1)
new_array

array([[3, 4, 6, 6, 7],
       [2, 4, 6, 7, 9],
       [2, 3, 5, 7, 7]])

In [134]:
# Sort the indexes of one of the arrays you just created

In [136]:
b1

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5]])

In [137]:
np.argsort(b1, axis=1)

array([[1, 3, 0, 4, 2],
       [1, 4, 2, 3, 0],
       [3, 0, 4, 1, 2]])

In [138]:
np.argsort(b1, axis=0)

array([[2, 1, 1, 2, 1],
       [0, 0, 0, 0, 2],
       [1, 2, 2, 1, 0]])

In [139]:
# Find the index with the maximum value in one of the arrays you've created

In [142]:
b1

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5]])

In [141]:
np.argmax(b1)

5

In [143]:
b2

array([[4, 1, 7, 5, 1],
       [4, 0, 9, 5, 8],
       [0, 9, 2, 6, 3]])

In [144]:
# let find the max of b2
np.argmax(b2)

7

In [145]:
# Find the index with the minimum value in one of the arrays you've created

In [146]:
# index with the minimum value
np.argmin(b1)

6

In [148]:
np.argmin(b2)

6

In [149]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created

In [151]:
b1

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5]])

In [153]:
np.argmax(b1, axis=1)

array([2, 0, 1])

In [154]:
np.argmax(b2, axis=1)

array([2, 2, 1])

In [155]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created

In [156]:
np.argmin(b1, axis=0)

array([2, 1, 1, 2, 1])

In [157]:
np.argmin(b2, axis=0)

array([2, 1, 2, 0, 0])

In [158]:
# Create an array of normally distributed random numbers

In [159]:
array= np.random.randint(1, 100, size=(10, 10))

In [160]:
array

array([[64,  3, 51,  7, 21, 73, 39, 18,  4, 89],
       [60, 14,  9, 90, 53,  2, 84, 92, 60, 71],
       [44,  8, 47, 35, 78, 81, 36, 50,  4,  2],
       [ 6, 54,  4, 54, 93, 63, 18, 90, 44, 34],
       [74, 62, 14, 95, 48, 15, 72, 78, 87, 62],
       [40, 85, 80, 82, 53, 24, 26, 89, 60, 41],
       [29, 15, 45, 65, 89, 71,  9, 88,  1,  8],
       [88, 63, 11, 81,  8, 35, 35, 33,  5, 41],
       [28,  7, 73, 72, 12, 34, 33, 48, 23, 62],
       [88, 37, 99, 44, 86, 91, 35, 65, 99, 47]])

In [161]:
# Create an array with 10 evenly spaced numbers between 1 and 100

In [168]:
even_array= np.arange(1, 100, 10)

In [169]:
even_array

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])